// Converts a trained weights JSON into a Rust weights module.
// Layer sizes are inferred from the array lengths.
// Usage: node tools/export-weights.mjs <weights.json> <output.rs>

import { readFileSync, writeFileSync } from 'node:fs';

const [, , input = 'wasm/engine/weights.json', output = 'wasm/engine/weights/medium.rs'] =
  process.argv;
const w = JSON.parse(readFileSync(input, 'utf8'));

const IN = 61;
const h1 = w.B1.length;
const h2 = w.B2.length;

const fmt = (v) => {
  if (!Number.isFinite(v)) throw new Error(`non-finite weight: ${v}`);
  const s = v.toFixed(6);
  return s.includes('.') ? s : s + '.0';
};
const arr = (name, values, len) => {
  if (values.length !== len) throw new Error(`${name}: expected ${len}, got ${values.length}`);
  return `pub static ${name}: [f32; ${len}] = [${values.map(fmt).join(', ')}];`;
};

const out = `//! Value-network weights. Generated by tools/export-weights.mjs — do not edit.

pub const TRAINED: bool = true;
pub const H1: usize = ${h1};
pub const H2: usize = ${h2};

${arr('W1', w.W1, IN * h1)}
${arr('B1', w.B1, h1)}
${arr('W2', w.W2, h1 * h2)}
${arr('B2', w.B2, h2)}
${arr('W3', w.W3, h2)}
pub static B3: f32 = ${fmt(w.B3)};
`;

writeFileSync(output, out);
console.log(`wrote ${output} (${h1}x${h2}, ${(out.length / 1024).toFixed(0)} KB source)`);
