// Converts wasm/engine/weights.json into wasm/engine/src/weights.rs.
// Usage: node tools/export-weights.mjs

import { readFileSync, writeFileSync } from 'node:fs';

const w = JSON.parse(readFileSync('wasm/engine/weights.json', 'utf8'));

const fmt = (v) => {
  if (!Number.isFinite(v)) throw new Error(`non-finite weight: ${v}`);
  const s = v.toFixed(6);
  return s.includes('.') ? s : s + '.0';
};
const arr = (name, values, len) => {
  if (values.length !== len) throw new Error(`${name}: expected ${len}, got ${values.length}`);
  return `pub static ${name}: [f32; ${len}] = [${values.map(fmt).join(', ')}];`;
};

const out = `//! Value-network weights. Generated by tools/export-weights.mjs — do not edit.

pub const TRAINED: bool = true;

${arr('W1', w.W1, 61 * 64)}
${arr('B1', w.B1, 64)}
${arr('W2', w.W2, 64 * 32)}
${arr('B2', w.B2, 32)}
${arr('W3', w.W3, 32)}
pub static B3: f32 = ${fmt(w.B3)};
`;

writeFileSync('wasm/engine/src/weights.rs', out);
console.log(`wrote weights.rs (${(out.length / 1024).toFixed(0)} KB source)`);
